[pytest]
markers =
    critical: Critical tests
    medium: Medium priority tests
    smoke: Smoke tests
    regression: Regression tests
    update: Update operations tests
    creation: Creation operations tests
    deletion: Deletion operations tests